import { useState } from 'react';
import type { Database } from '../../services/storageService';
import type { CallReview } from '../../types/CallReview';
import { cleanCallIdFromFilename, id } from '../../utils/text';
import { findDuplicate } from '../../services/duplicateService';
import { generateCallDraft, transcribeAudio } from '../../services/openaiService';
import { upsertCall } from '../../services/callsService';
type Status='queued'|'transcribing'|'transcript_ready'|'drafting'|'ready_for_review'|'saved'|'failed'|'duplicate_possible';
interface Row { id:string; file:File; status:Status; transcript?:string; draft?:Partial<CallReview>; error?:string; reviewed?:boolean; }
export function BatchTranscribe({ db, setDb }: { db:Database; setDb:(db:Database)=>void }) { const [rows,setRows]=useState<Row[]>([]); const [paused,setPaused]=useState(false);
 const add=(files:FileList|null)=> files && setRows(r=>[...r,...Array.from(files).map(file=>({id:id('row'), file, status:'queued' as Status}))]);
 async function start(){ setPaused(false); for (const row of rows) { if (paused) break; const latest = rows.find(r=>r.id===row.id); if (!latest || !['queued','failed'].includes(latest.status)) continue; try { update(row.id,{status:'transcribing'}); const transcript=await transcribeAudio(db.settings,row.file); update(row.id,{status:'transcript_ready', transcript}); update(row.id,{status:'drafting'}); const { call }=await generateCallDraft(db.settings,{transcript,file:row.file}); call.call_id ||= cleanCallIdFromFilename(row.file.name); const dup=findDuplicate(call, db.calls); update(row.id,{status:dup?'duplicate_possible':'ready_for_review', draft:call}); } catch(e:any){ update(row.id,{status:'failed', error:e.message}); } } }
 const update=(rid:string, patch:Partial<Row>)=>setRows(r=>r.map(x=>x.id===rid?{...x,...patch}:x));
 const save=(row:Row)=>{ if(!row.draft) return; setDb(upsertCall(db,row.draft)); update(row.id,{status:'saved'}); };
 return <div className="panel"><h3>Batch Transcribe</h3><p className="muted">Files process sequentially. A failed file will not stop the queue.</p><div className="drop"><input type="file" multiple accept="audio/wav,audio/mp3,audio/mpeg,audio/m4a,audio/webm,audio/ogg" onChange={e=>add(e.target.files)}/><span>Drop or choose multiple audio files</span></div><div className="row"><button className="primary" onClick={start}>Start batch</button><button onClick={()=>setPaused(true)}>Pause after current</button><button onClick={()=>rows.filter(r=>r.status==='ready_for_review').forEach(save)}>Save all reviewed</button><button onClick={()=>setRows(rows.filter(r=>r.status!=='saved'))}>Clear completed</button></div><div className="queue">{rows.map(r=><div className="queue-row" key={r.id}><strong>{r.file.name}</strong><span className={'badge '+(r.status==='failed'?'red':r.status==='saved'?'green':'blue')}>{r.status}</span><span>{r.error}</span><div className="row"><button onClick={()=>alert(r.transcript || 'No transcript yet')}>View transcript</button><button onClick={()=>r.draft && alert(JSON.stringify(r.draft,null,2))}>Review draft</button><button disabled={!r.draft} onClick={()=>save(r)}>Save call</button><button onClick={()=>update(r.id,{status:'queued', error:undefined})}>Retry</button><button onClick={()=>setRows(rows.filter(x=>x.id!==r.id))}>Remove</button></div></div>)}</div></div>; }
