import { useState } from 'react';
import type { Database } from '../../services/storageService';
import { askAi } from '../../services/openaiService';
import { saveInsight } from '../../services/insightsService';
export function AskAiPanel({ db, setDb, contextType='project', relatedId, onClose }: { db:Database; setDb:(db:Database)=>void; contextType?:'project'|'call'|'issue'; relatedId?:string; onClose?:()=>void }) {
 const [q,setQ]=useState(''); const [answer,setAnswer]=useState(''); const [busy,setBusy]=useState(false); const [err,setErr]=useState('');
 const context = contextType === 'call' ? { call: db.calls.find(c=>c.id===relatedId), evidence: db.evidence.filter(e=>e.call_id===relatedId), issues: db.issues.filter(i=>i.linked_call_ids.includes(relatedId||'')) } : contextType === 'issue' ? { issue: db.issues.find(i=>i.id===relatedId), evidence: db.evidence.filter(e=>e.issue_id===relatedId), calls: db.calls.filter(c=>c.linked_issue_ids.includes(relatedId||'')), experiments: db.experiments.filter(e=>e.linked_issue_id===relatedId) } : { activeIssues: db.issues.filter(i=>!['resolved','ignored'].includes(i.status)).slice(0,5), recentCalls: db.calls.slice(0,5), experiments: db.experiments, memory: db.memory.slice(0,8) };
 async function run(){ setBusy(true); setErr(''); try{ const r=await askAi(db.settings,{ question:q, contextType, context }); setAnswer(r.answer || JSON.stringify(r,null,2)); } catch(e:any){ setErr(e.message || 'AI failed'); setAnswer('Local recommendation:\n- Focus on the highest severity active issue.\n- Attach exact call evidence before changing prompts.\n- Define one success metric before testing.'); } finally{ setBusy(false); } }
 function save(){ setDb(saveInsight(db,{ title:q.slice(0,60)||'Ask AI snapshot', summary:answer.slice(0,240), question:q, answer, context_type:contextType, related_call_id:contextType==='call'?relatedId:undefined, related_issue_id:contextType==='issue'?relatedId:undefined, raw_json:answer })); }
 return <section className="ask-panel"><div className="row between"><div><h3>Ask AI</h3><p className="muted">Context: {contextType === 'project' ? 'Whole project' : contextType === 'call' ? 'Current call' : 'Current issue'}</p></div>{onClose && <button onClick={onClose}>Close</button>}</div><textarea value={q} onChange={e=>setQ(e.target.value)} placeholder="Ask for exact next steps, an experiment, or a meeting-ready summary..."/><div className="row"><button className="primary" onClick={run} disabled={busy || !q.trim()}>{busy?'Asking...':'Ask'}</button><button onClick={save} disabled={!answer}>Save snapshot</button></div>{err && <p className="error">{err}</p>}{answer && <pre className="answer">{answer}</pre>}</section>;
}
