import { useState } from 'react';
import type { Database } from '../services/storageService';
import type { Experiment } from '../types/Experiment';
import { upsertExperiment, deleteExperiment } from '../services/experimentsService';
import { generateExperimentDraft } from '../services/openaiService';
import { Field } from '../components/ui/Field';
import { Badge } from '../components/ui/Badge';
const blank: Partial<Experiment> = { date: new Date().toISOString().slice(0,10), experiment_name:'', changed_setting:'', old_value:'', new_value:'', expected_effect:'', actual_effect:'', result:'inconclusive', related_call_ids:[], notes:'' };
export function ExperimentsPage({ db, setDb }: { db: Database; setDb: (db: Database) => void }) { const [draft,setDraft]=useState<Partial<Experiment>>(blank); const [text,setText]=useState(''); const [err,setErr]=useState(''); async function ai(){ setErr(''); try{ setDraft({...draft, ...(await generateExperimentDraft(db.settings,text))}); } catch(e:any){ setErr(e.message || 'Failed'); } } return <main className="page"><div className="page-head"><div><h1>Experiments</h1><p>Track prompt, workflow, integration, and voice changes against call evidence.</p></div></div><section className="grid two"><div className="panel form-grid"><Field label="AI Autofill Experiment"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Describe what you changed and what happened..."/></Field><button type="button" onClick={ai}>Generate experiment draft</button>{err && <p className="error">{err}</p>}<Field label="Name"><input value={draft.experiment_name||''} onChange={e=>setDraft({...draft,experiment_name:e.target.value})}/></Field><Field label="Changed setting"><input value={draft.changed_setting||''} onChange={e=>setDraft({...draft,changed_setting:e.target.value})}/></Field><Field label="Old value"><input value={draft.old_value||''} onChange={e=>setDraft({...draft,old_value:e.target.value})}/></Field><Field label="New value"><input value={draft.new_value||''} onChange={e=>setDraft({...draft,new_value:e.target.value})}/></Field><Field label="Expected effect"><textarea value={draft.expected_effect||''} onChange={e=>setDraft({...draft,expected_effect:e.target.value})}/></Field><Field label="Actual effect"><textarea value={draft.actual_effect||''} onChange={e=>setDraft({...draft,actual_effect:e.target.value})}/></Field><Field label="Result"><select value={draft.result} onChange={e=>setDraft({...draft,result:e.target.value as any})}><option>better</option><option>worse</option><option>no_change</option><option>inconclusive</option></select></Field><Field label="Notes"><textarea value={draft.notes||''} onChange={e=>setDraft({...draft,notes:e.target.value})}/></Field><button type="button" className="primary" onClick={()=>{setDb(upsertExperiment(db,draft)); setDraft(blank);}}>Save experiment</button></div><div className="panel"><h2>Experiment list</h2>{db.experiments.map(e=><div className="list-row experiment-row" key={e.id} role="button" tabIndex={0} onClick={()=>setDraft(e)} onKeyDown={ev=>ev.key==='Enter'&&setDraft(e)}><strong>{e.experiment_name}</strong><span>{e.changed_setting}</span><Badge tone="blue">{e.result}</Badge><button type="button" onClick={(ev)=>{ev.stopPropagation(); setDb(deleteExperiment(db,e.id));}}>Delete</button></div>)}</div></section></main>; }
