import { useState } from 'react';
import type { Database } from '../services/storageService';
import type { Issue } from '../types/Issue';
import { Badge } from '../components/ui/Badge';
import { Modal } from '../components/ui/Modal';
import { AskAiPanel } from '../components/ask-ai/AskAiPanel';
import { setIssueStatus, upsertIssue } from '../services/issuesService';
import { secondsToClock } from '../utils/dates';

export function IssuesPage({ db, setDb, selectedIssueId, clearSelected }: { db: Database; setDb: (db: Database) => void; selectedIssueId?: string; clearSelected: () => void }) {
  const [local, setLocal] = useState<Issue | null>(null);
  const selected = selectedIssueId ? db.issues.find(i => i.id === selectedIssueId) || null : local;
  return <main className="page"><div className="page-head"><div><h1>Issues</h1><p>Recurring problems linked to exact calls and evidence.</p></div><button className="primary" onClick={() => setLocal({ id: '', title: '', category: 'Other', severity: 'medium', status: 'active', description: '', suggested_fix: '', notes: '', linked_call_ids: [], created_at: '', updated_at: '' })}>Add issue</button></div><section className="panel issue-grid">{db.issues.map(i => <article className="issue-card" key={i.id} onClick={() => setLocal(i)}><div className="row between"><h3>{i.title}</h3><Badge tone={i.severity === 'high' ? 'red' : i.severity === 'medium' ? 'yellow' : 'neutral'}>{i.severity}</Badge></div><Badge tone="blue">{i.status}</Badge><p>{i.description}</p><p><b>Calls:</b> {i.linked_call_ids.length}</p></article>)}</section>{selected && <IssueDetail issue={selected} db={db} setDb={setDb} onClose={() => { setLocal(null); clearSelected(); }} />}</main>;
}
function IssueDetail({ issue, db, setDb, onClose }: { issue: Issue; db: Database; setDb: (db: Database) => void; onClose: () => void }) {
  const [draft, setDraft] = useState(issue); const [ask, setAsk] = useState(false); const evidence = db.evidence.filter(e => e.issue_id === issue.id); const calls = db.calls.filter(c => issue.linked_call_ids.includes(c.id));
  const copy = ['Issue: ' + issue.title, 'Affected calls: ' + calls.map(c => c.call_id).join(', '), 'Evidence:', ...evidence.map(e => '- ' + (db.calls.find(c => c.id === e.call_id)?.call_id || e.call_id) + ', ' + secondsToClock(e.timestamp_start_seconds) + ', ' + e.quote_or_transcript_excerpt + ', why it matters: ' + e.explanation), 'Suggested fix: ' + issue.suggested_fix, 'Experiment: ' + (db.experiments.find(e => e.id === issue.experiment_id)?.experiment_name || 'None yet'), 'Open questions: What is the smallest setting or prompt change to test next?'].join('\n');
  return <Modal title={issue.title || 'Issue detail'} onClose={onClose} wide><div className="detail-grid"><section className="form-grid"><label className="field"><span>Title</span><input value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} /></label><label className="field"><span>Severity</span><select value={draft.severity} onChange={e => setDraft({ ...draft, severity: e.target.value as any })}><option>low</option><option>medium</option><option>high</option></select></label><label className="field"><span>Status</span><select value={draft.status} onChange={e => setDraft({ ...draft, status: e.target.value as any })}><option>active</option><option>investigating</option><option>testing</option><option>improving</option><option>resolved</option><option>ignored</option></select></label><label className="field"><span>Description</span><textarea value={draft.description} onChange={e => setDraft({ ...draft, description: e.target.value })} /></label><label className="field"><span>Suggested fix</span><textarea value={draft.suggested_fix} onChange={e => setDraft({ ...draft, suggested_fix: e.target.value })} /></label><label className="field"><span>Operational notes</span><textarea value={draft.notes} onChange={e => setDraft({ ...draft, notes: e.target.value })} /></label><button className="primary" onClick={() => setDb(upsertIssue(db, draft))}>Save issue</button></section><section><h3>Linked calls</h3>{calls.map(c => <div className="mini" key={c.id}><strong>{c.call_id}</strong><p>{c.call_summary}</p></div>)}<h3>Evidence moments</h3>{evidence.map(e => <div className="evidence" key={e.id}><Badge>{e.moment_type}</Badge><b>{secondsToClock(e.timestamp_start_seconds)}</b><blockquote>{e.quote_or_transcript_excerpt}</blockquote><p>{e.explanation}</p></div>)}<div className="row wrap"><button onClick={() => setDb(setIssueStatus(db, issue.id, 'testing'))}>Mark testing</button><button onClick={() => setDb(setIssueStatus(db, issue.id, 'resolved'))}>Resolve</button><button onClick={() => setDb(setIssueStatus(db, issue.id, 'active'))}>Reopen</button><button>Start experiment</button><button onClick={() => setAsk(!ask)}>Ask AI</button><button onClick={() => navigator.clipboard.writeText(copy)}>Copy issue evidence summary</button></div>{ask && <AskAiPanel db={db} setDb={setDb} contextType="issue" relatedId={issue.id} />}</section></div></Modal>;
}
